
region_name       = "us-east-1"
vpc_cidr_block    = "10.0.0.0/16"
vpc_tag_name      = "vpc-Terraform"
ig_tag_name       = "Ig-Terraform"
subnet_cidr_block = "10.0.0.0/24"
subnet_az         = "us-east-1a"
subnet_tag_name   = "Public-Subnet-Terraform"
rt_cidr_block     = "0.0.0.0/0"
rt_tag_name       = "Public-RT-Terraform"
ec2_az            = "us-east-1a"
ec2_instance_type = "t2.micro"
key_name          = "devops-prod-key"
